name: AstraLand-OneBlock
version: 1.0.0-SNAPSHOT
main: com.astraland.oneblock.OneBlock
api-version: "1.21"
description: AstraLand - Module OneBlock
authors: [AstraLand]

commands:
  oneblock:
    description: Commandes OneBlock
    aliases: [ob, one]
    usage: /oneblock <create|home|info|phase|top>
  balance:
    description: Voir son solde de pièces
    aliases: [bal, money]
    usage: /balance [joueur]
  pay:
    description: Envoyer des pièces à un joueur
    usage: /pay <joueur> <montant>
