name: AstraLand-Skyblock
version: 1.0.0-SNAPSHOT
main: com.astraland.skyblock.Skyblock
api-version: "1.21"
description: AstraLand - Module Skyblock
authors: [AstraLand]

commands:
  island:
    description: Commandes Skyblock
    aliases: [is, sb, skyblock]
    usage: /island <create|home|sethome|invite|join|kick|leave|delete|info|top|visit|warp|warps|setwarp|delwarp|lock|unlock|pvp|ban|unban|banlist|coop|uncoop|chat|level|scan|setname|expel|settings|generator|help>
  balance:
    description: Voir son solde de pièces
    aliases: [bal, money]
    usage: /balance [joueur]
  pay:
    description: Envoyer des pièces à un joueur
    usage: /pay <joueur> <montant>
  shop:
    description: Ouvre le shop du mode de jeu
    usage: /shop
  ah:
    description: Hôtel des ventes
    aliases: [auction, bazaar]
    usage: /ah [sell <prix>]
  sell:
    description: Vendre des items du shop
    aliases: [sellall]
    usage: /sell all
  isadmin:
    description: Administration des îles Skyblock
    aliases: [sbadmin, islandadmin]
    usage: /isadmin <setlevel|reset|visit|info|setbalance> <joueur> [valeur]
    permission: astraland.admin
    default: op
  givemoney:
    description: Donner de l'argent à un joueur (admin)
    aliases: [addmoney, eco-give]
    usage: /givemoney <joueur> <montant>
    permission: astraland.admin
    permission-message: "&cTu n'as pas la permission d'utiliser cette commande."
    default: op
