name: AstraLand-Spleef
version: 1.0.0-SNAPSHOT
main: com.astraland.spleef.Spleef
api-version: "1.21"
description: AstraLand - Module Spleef
authors: [AstraLand]

commands:
  spleef:
    description: Commandes Spleef
    usage: /spleef <join|leave|list|create|setspawn|start|stop>
  balance:
    description: Voir son solde de pièces
    aliases: [bal, money]
    usage: /balance [joueur]
  pay:
    description: Envoyer des pièces à un joueur
    usage: /pay <joueur> <montant>
  shop:
    description: Ouvre le shop du mode de jeu
    usage: /shop
  ah:
    description: Hôtel des ventes
    aliases: [auction, bazaar]
    usage: /ah [sell <prix>]
  givemoney:
    description: Donner de l'argent à un joueur (admin)
    aliases: [addmoney, eco-give]
    usage: /givemoney <joueur> <montant>
    permission: astraland.admin
    permission-message: "&cTu n'as pas la permission d'utiliser cette commande."
    default: op
