name: AstraLand-Bedwars
version: 1.0.0-SNAPSHOT
main: com.astraland.bedwars.Bedwars
api-version: "1.21"
description: AstraLand - Module Bedwars
authors: [AstraLand]

commands:
  bedwars:
    description: Commandes Bedwars
    aliases: [bw]
    usage: /bedwars <join|leave|list|create|setbed|setspawn|start>
